/* jconfig.h for ESP32 */
#define HAVE_STDDEF_H
#define HAVE_STDLIB_H
#define HAVE_UNSIGNED_CHAR
#define HAVE_UNSIGNED_SHORT
#undef NEED_BSD_STRINGS
#undef NEED_SYS_TYPES_H
#undef NEED_FAR_POINTERS
#undef INCOMPLETE_TYPES_BROKEN
#ifdef JPEG_INTERNALS
#undef RIGHT_SHIFT_IS_UNSIGNED
#endif
